export const SET_AUTH_BEGIN = "SET_AUTH_BEGIN";
export const SET_AUTH_SUCCESS = "SET_AUTH_SUCCESS";
export const SET_AUTH_FAILED = "SET_AUTH_FAILED";

export const SET_USER_BEGIN = "SET_USER_BEGIN";
export const SET_USER_LIST = "SET_USER_LIST";
export const SET_USER_UPDATE = "SET_USER_UPDATE";
export const SET_USER_DELETE = "SET_USER_DELETE";
export const SET_USER_ADD = "SET_USER_ADD";

export const SET_PRODUCTLINE_BEGIN = "SET_PRODUCTLINE_BEGIN";
export const SET_PRODUCTLINE_LIST = "SET_PRODUCTLINE_LIST";

export const SET_PRODUCT_BEGIN = "SET_PRODUCT_BEGIN";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";

export const SET_REQUEST_BEGIN = "SET_REQUEST_BEGIN";
export const SET_REQUEST_LIST = "SET_REQUEST_LIST";
export const SET_REQUEST_ADD = "SET_REQUEST_ADD";
export const SET_REQUEST_FAILED = "SET_REQUEST_FAILED";
